services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Options\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources'
            - '../../../../Domain/WriteModel/Model'
            - '../../../../Domain/WriteModel/Exception'

    Tulia\Cms\Options\Infrastructure\Framework\Config\YamlOptionsProvider:
        bind:
            $definitions: '%cms.options.definitions%'

    Tulia\Cms\Shared\Infrastructure\Mail\MailerConfigurationProviderInterface:
        class: Tulia\Cms\Options\Infrastructure\Mailer\OptionsAwareMailerConfigurationProvider

    Tulia\Cms\Options\Domain\ReadModel\Options:
        lazy: true

    Tulia\Cms\Options\Domain\WriteModel\Service\RegisteredOptionsRegistry:
        arguments:
            $providers: !tagged_iterator options.provider
