services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Options\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Options\Application\Service\RegisteredOptionsRegistry:
        bind:
            $definitions: '%cms.options.definitions%'

    Tulia\Cms\Shared\Infrastructure\Mail\MailerConfigurationProviderInterface:
        class: Tulia\Cms\Options\Infrastructure\Mailer\OptionsAwareMailerConfigurationProvider
