framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/Widget/Infrastructure/Framework/Resources/translations'
doctrine:
    orm:
        mappings:
            Tulia\Cms\Widget\Domain\WriteModel\Model:
                type: xml
                dir: '%cms.core_dir%/Cms/Widget/Infrastructure/Framework/Resources/config/orm/mapping'
                is_bundle: false
                prefix: Tulia\Cms\Widget\Domain\WriteModel\Model
                alias: CmsWidget
cms:
    twig:
        loader:
            array:
                templates:
                    widget:
                        template: "{% extends [ '@theme/widget.tpl', '@parent/widget.tpl', '@widget-base/widget.tpl' ] %}"
    templating:
        paths:
            - { name: backend/widget, path: '%cms.core_dir%/Cms/Widget/Infrastructure/Framework/Resources/views/backend' }
            - { name: widget-base, path: '%cms.core_dir%/Cms/Widget/Infrastructure/Framework/Resources/views/widget-base' }
    widgets:
        internal.features:
            classname: 'Tulia\Cms\Widget\Infrastructure\Cms\Widget\Predefined\Features\FeaturesWidget'
            views: '%cms.core_dir%/Cms/Widget/Infrastructure/Framework/Resources/views/widget/features'
            name: widget.features.name
            description: widget.features.description
            translation_domain: widgets
            fields:
                features:
                    type: repeatable
                    name: Features
                label:
                    type: text
                    name: title
                    parent: features
                description:
                    type: text
                    name: description
                    parent: features
                icon:
                    type: text
                    name: icon
                    parent: features
        internal.text:
            classname: 'Tulia\Cms\Widget\Infrastructure\Cms\Widget\Predefined\Text\TextWidget'
            views: '%cms.core_dir%/Cms/Widget/Infrastructure/Framework/Resources/views/widget/text'
            name: widget.text.name
            description: widget.text.description
            translation_domain: widgets
            fields:
                content:
                    type: wysiwyg
                    name: content
    content_building:
        content_type:
            widget:
                layout_builder: 'Tulia\Cms\Widget\Infrastructure\Presentation\TwigWidgetContentTypeLayoutBuilder'
                multilingual: false
                configurable: false
        content_type_entry:
            widget:
                type: widget
                name: Widgets
                icon: null
                controller: null
                is_routable: false
                is_hierarchical: false
                routing_strategy: null
                layout:
                    sections:
                        main:
                            groups:
                                widget_options:
                                    name: Widget options
                                    fields: [ ]
