services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Widget\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources'
            - '../../../../Domain/WriteModel/Model'
            - '../../../../Domain/WriteModel/Exception'
            - '../../../../Domain/WriteModel/Event'
            - '../../../../Domain/ReadModel/Model'

    Tulia\Cms\Widget\Infrastructure\Framework\Twig\Extension\WidgetExtension:
        bind:
            $storage: '@Tulia\Cms\Widget\Infrastructure\Persistence\Doctrine\Dbal\DbalWidgetStorage'

    Tulia\Cms\Widget\Domain\Renderer\RendererInterface:
        class: Tulia\Cms\Widget\Domain\Renderer\Renderer
        bind:
            $storage: '@Tulia\Cms\Widget\Infrastructure\Persistence\Doctrine\Dbal\DbalWidgetStorage'

    Tulia\Cms\Widget\Infrastructure\Persistence\ContainerProvider\WidgetTypeContainerProvider:
        bind:
            $widgets: '%cms.widgets%'
            $configuration: '%cms.content_builder.content_type_entry.config%'
