services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\SearchAnything\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources'
            - '../../../../Domain/WriteModel/Model'

    Tulia\Cms\SearchAnything\Domain\WriteModel\Service\DocumentCollectorRegistry:
        arguments:
            $collectors: !tagged_iterator search_anything.document_collector

    Tulia\Cms\SearchAnything\Domain\WriteModel\Service\DocumentCollectorRegistryInterface:
        '@Tulia\Cms\SearchAnything\Domain\WriteModel\Service\DocumentCollectorRegistry'
