framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/FrontendToolbar/Framework/Resources/translations'
    templating:
        paths:
            - { name: cms/frontend_toolbar, path: '%cms.core_dir%/Cms/FrontendToolbar/Framework/Resources/views/frontend' }
    public_paths:
        '%cms.core_dir%/Cms/FrontendToolbar/Framework/Resources/public/dist': '/core/frontend-toolbar'
