services:
    _defaults:
        autowire: true
        autoconfigure: true
    _instanceof:
        Tulia\Component\Importer\FileReader\FileReaderInterface:
            tags: [ importer.file_reader ]

    Tulia\Component\Importer\:
        resource: '../../../../../../../Component/importer/src/*'
        exclude:
            - '../../../../../../../Component/importer/src/Implementation/*'
            - '../../../../../../../Component/importer/src/Exception/*'
            - '../../../../../../../Component/importer/src/Schema/*'
            - '../../../../../../../Component/importer/src/Structure/*'

    Tulia\Component\Importer\Schema\Schema:
        factory: [ 'Tulia\Component\Importer\Implementation\Symfony\SchemaFromContainerFactory', 'build' ]
        bind:
            $objects: '%cms.importer.objects%'
            
    Tulia\Component\Importer\Parameters\ParametersProviderInterface:
        '@Tulia\Component\Importer\Parameters\ArrayParametersProvider'
    
    Tulia\Component\Importer\Parameters\ArrayParametersProvider:
        bind:
            $parameters:
                cms.core_dir: '%cms.core_dir%'
                kernel.project_dir: '%kernel.project_dir%'
