services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $publicDir: '%kernel.public_dir%'
            $rootDir: '%kernel.project_dir%'
            $cmsCoreDir: '%cms.core_dir%'
            $assetsPublicPaths: '%cms.assets.public_paths%'
            $environment: '%kernel.environment%'

    Tulia\Cms\Platform\:
        resource: '../../../../../**'
        exclude: '../../../../../{Infrastructure/Framework/Resources,Domain/WriteModel,Shared}'

    Tulia\Cms\Shared\Infrastructure\Utils\DateTime\DateFormatterInterface:
        class: Tulia\Cms\Platform\Infrastructure\Utilities\DateTime\DateFormatterTranslatorAware

    Tulia\Cms\Platform\Shared\Document\DocumentInterface:
        class: Tulia\Cms\Platform\Shared\Document\Document

    Tulia\Cms\Platform\UserInterface\Console\Command\AssetsPublish:
        tags:
            - { name: console.command, command: 'assets:publish' }

    Tulia\Cms\Platform\Infrastructure\Framework\Theme\Storage\DirectoryDiscoveryStorage:
        bind:
            $extensionsDirectories:
                '%kernel.project_dir%/extension/theme': 'Tulia\Theme'

    Tulia\Component\Theme\Storage\StorageInterface: '@Tulia\Cms\Platform\Infrastructure\Framework\Theme\Storage\DirectoryDiscoveryStorage'

    Tulia\Cms\Platform\Domain\Service\DynamicConfigurationInterface:
        class: Tulia\Cms\Platform\Infrastructure\Filesystem\FilesystemDynamicConfiguration
        bind:
            $configFilename: '%kernel.project_dir%/config/dynamic.php'
            $config: '%cms.dynamic_config%'

    Tulia\Cms\Platform\Application\Service\FrameworkCacheService:
        bind:
            $kernelCacheFilepath: '%kernel.cache_file%'

    Tulia\Component\Routing\Website\WebsiteInterface:
        class: Tulia\Component\Routing\Website\Website
        factory: Tulia\Cms\Platform\Infrastructure\Framework\Routing\WebsiteFactory::factory

    Tulia\Cms\Platform\Infrastructure\Framework\Routing\RoutingLoader:
        decorates: routing.loader
        arguments: ['@.inner']

    Tulia\Cms\Platform\Infrastructure\Framework\Routing\UrlGenerator:
        decorates: Symfony\Component\Routing\Generator\UrlGeneratorInterface
        arguments: ['@.inner']

    Tulia\Cms\Platform\Infrastructure\Framework\Routing\Router:
        decorates: router
        arguments: ['@.inner']

    #Tulia\Cms\Security\Framework\Security\Http\HttpUtils:
    #    decorates: security.http_utils
    #    arguments: ['@.inner']
    #    calls:
    #        - setWebsite: ['@Tulia\Component\Routing\Website\WebsiteInterface']

    security.http_utils:
        class: Tulia\Cms\Security\Framework\Security\Http\HttpUtils
        calls:
            - setWebsite: ['@Tulia\Component\Routing\Website\WebsiteInterface']
