services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Component\Templating\:
        resource: '../../../../../../../Component/templating/src/*'

    Tulia\Component\Templating\Twig\Loader\AdvancedFilesystemLoader:
        bind:
            $paths: '%cms.templating.paths%'

    Tulia\Component\Templating\Twig\Loader\LazyArrayLoader:
        bind:
            $templates: '%cms.twig.loader.array.templates%'

    Twig\Extension\StringLoaderExtension: ~
