services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Shared\Domain\WriteModel\UuidGeneratorInterface:
        class: Tulia\Cms\Shared\Infrastructure\Utils\Uuid\RamseyUuidGenerator

    Tulia\Cms\Shared\Infrastructure\Utils\Annotations\AnnotationsReaderInterface:
        class: Tulia\Cms\Shared\Infrastructure\Utils\Annotations\AnnotationsReader

    Tulia\Cms\Shared\Domain\WriteModel\Service\SluggerInterface:
        class: Tulia\Cms\Shared\Infrastructure\Utils\Slug\SimpleSlugGenerator

    Tulia\Cms\Shared\Infrastructure\Utils\Hydrator\HydratorInterface:
        class: Tulia\Cms\Shared\Infrastructure\Utils\Hydrator\OcramiusHydrator

    Tulia\Cms\Shared\Application\UseCase\TransactionalSessionInterface:
        class: Tulia\Cms\Shared\Infrastructure\Persistence\Doctrine\DoctrineTransactionalSession
