monolog:
    handlers:
        main:
            type: buffer
            handler: grouped
            channels: [ "app" ]
            level: debug
            bubble: false
        default:
            type: buffer
            handler: grouped
            channels: [ "!app" ]
            level: error
            bubble: false
        grouped:
            type:    whatfailuregroup
            members: [ "streamed" ]
        streamed:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level: error
            include_stacktraces: true
