framework:
    public_paths:
        - { source: '%cms.core_dir%/Cms/TuliaEditor/Infrastructure/Framework/Resources/public/tulia-editor/dist', target: '/core/tulia-editor' }
    translator:
        paths:
            - '%cms.core_dir%/Cms/TuliaEditor/Infrastructure/Framework/Resources/translations'
    templating:
        paths:
            - { name: backend/tulia-editor, path: '%cms.core_dir%/Cms/TuliaEditor/Infrastructure/Framework/Resources/views' }
    assetter:
        assets:
            tulia_editor:
                group: body
                scripts:
                    - /assets/core/tulia-editor/tulia-editor.js
                styles:
                    - /assets/core/tulia-editor/main.css
                require: [ lodash, vue, quill ]
            tulia_editor_extensions: ~
            tulia_editor_blocks: ~
cms:
    content_building:
        data_types:
            mapping:
                tulia_editor:
                    label: Tulia Editor
                    flags: [ compilable, renderable ]
                    classname: 'Tulia\Cms\TuliaEditor\Infrastructure\Framework\Form\FormType\TuliaEditorType'
                    builder: 'Tulia\Cms\TuliaEditor\Infrastructure\Framework\Form\FormType\TuliaEditorTypeBuilder'
