framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/User/Infrastructure/Framework/Resources/translations'

twig:
    form_themes:
        - '@backend/user/form/user_form_layout.tpl'

cms:
    templating:
        paths:
            - { name: cms/user, path: '%cms.core_dir%/Cms/User/Infrastructure/Framework/Resources/views/frontend' }
            - { name: backend/user, path: '%cms.core_dir%/Cms/User/Infrastructure/Framework/Resources/views/backend' }
    content_building:
        data_types:
            mapping:
                user:
                    label: User
                    classname: 'Tulia\Cms\User\Infrastructure\Framework\Form\FormType\UserTypeahead\UserTypeaheadType'
                    builder: 'Tulia\Cms\User\Infrastructure\Framework\Form\FormType\UserTypeahead\UserTypeaheadTypeBuilder'
                    constraints: [ required ]
#                user_roles:
#                    label: User roles
#                    classname: 'Tulia\Cms\User\Infrastructure\Framework\Form\FormType\UserRoles\UserRolesType'
#                    constraints: [ required ]
#                    only_for_types: [ user ]
#                user_avatar:
#                    label: User avatar
#                    classname: 'Tulia\Cms\User\Infrastructure\Framework\Form\FormType\UserAvatar\UserAvatarType'
#                    builder: 'Tulia\Cms\User\Infrastructure\Framework\Form\FormType\UserAvatar\UserAvatarBuilder'
#                    handler: 'Tulia\Cms\User\Infrastructure\Framework\Form\FormType\UserAvatar\UserAvatarHandler'
#                    constraints: [ required ]
#                    only_for_types: [ user ]
#                user_remove_avatar:
#                    label: User remove avatar
#                    classname: 'Tulia\Cms\Platform\Infrastructure\Framework\Form\FormType\YesNoType'
#                    constraints: [ required ]
#                    only_for_types: [ user ]
        constraint_types:
            mapping:
                user_email_unique:
                    classname: 'Tulia\Cms\User\Infrastructure\Framework\Validator\Constraints\EmailUnique'
                    label: Unique user e-mail address
                password:
                    classname: 'Tulia\Cms\User\Infrastructure\Framework\Validator\Constraints\Password'
                    label: Password consistent with the Passwords Policy
        content_type:
            user:
                layout_builder: 'Tulia\Cms\User\Infrastructure\Presentation\TwigUserContentTypeLayoutBuilder'
                multilingual: false
                configurable: false
            my_account:
                layout_builder: 'Tulia\Cms\User\Infrastructure\Presentation\TwigMyAccountContentTypeLayoutBuilder'
                multilingual: false
                configurable: false
        content_type_entry:
            user:
                type: user
                name: Users
                icon: null
                controller: null
                is_routable: false
                is_hierarchical: false
                routing_strategy: null
                layout:
                    sections:
                        sidebar:
                            groups:
                                security:
                                    name: Security
                                    fields:
                                        my_test_field:
                                            type: text
                                            name: My text field
                                            #constraints:
                                            #    - code: required
            my_account:
                type: my_account
                name: My account
                icon: null
                controller: null
                is_routable: false
                is_hierarchical: false
                routing_strategy: null
                layout:
                    sections:
                        main:
                            groups:
                                main:
                                    name: My account
                                    fields:
                                        name:
                                            type: text
                                            name: Name
                                        locale:
                                            type: locale
                                            name: Locale
                                        avatar:
                                            type: user_avatar
                                            name: null
                                        remove_avatar:
                                            type: user_remove_avatar
                                            name: Remove avatar
