framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/User/Infrastructure/Framework/Resources/translations'

twig:
    form_themes:
        - '@backend/user/form/user_form_layout.tpl'

doctrine:
    orm:
        mappings:
            Tulia\Cms\User\Domain\WriteModel\Model:
                type: xml
                dir: '%cms.core_dir%/Cms/User/Infrastructure/Framework/Resources/config/orm/mapping'
                is_bundle: false
                prefix: Tulia\Cms\User\Domain\WriteModel\Model
                alias: CmsUser

cms:
    options:
        definitions:
            users.password.min_length:
                value: 4
            users.password.min_digits:
                value: 1
            users.password.min_special_chars:
                value: 1
            users.password.min_big_letters:
                value: 1
            users.password.min_small_letters:
                value: 1
            users.username.min_length:
                value: 4
    templating:
        paths:
            - { name: cms/user, path: '%cms.core_dir%/Cms/User/Infrastructure/Framework/Resources/views/frontend' }
            - { name: backend/user, path: '%cms.core_dir%/Cms/User/Infrastructure/Framework/Resources/views/backend' }
    content_building:
        data_types:
            mapping:
                user:
                    label: User
                    classname: 'Tulia\Cms\User\Infrastructure\Framework\Form\FormType\UserTypeahead\UserTypeaheadType'
                    builder: 'Tulia\Cms\User\Infrastructure\Framework\Form\FormType\UserTypeahead\UserTypeaheadTypeBuilder'
                    constraints: [ required ]
        constraint_types:
            mapping:
                user_email_unique:
                    classname: 'Tulia\Cms\User\Infrastructure\Framework\Validator\Constraints\EmailUnique'
                    label: Unique user e-mail address
                password:
                    classname: 'Tulia\Cms\User\Infrastructure\Framework\Validator\Constraints\Password'
                    label: Password consistent with the Passwords Policy
        content_type:
            user:
                layout_builder: 'Tulia\Cms\User\Infrastructure\Presentation\TwigUserContentTypeLayoutBuilder'
                multilingual: false
                configurable: false
        content_type_entry:
            user:
                type: user
                name: Users
                icon: null
                controller: null
                is_routable: false
                is_hierarchical: false
                routing_strategy: null
                layout: ~
