.PHONY: deploy
deploy:
	${PHPROOT} php bin/console deployer:detect \
	&& php vendor/bin/dep deploy

.PHONY: fix-vendor-permissions
fix-vendor-permissions:
	sudo chmod 0777 vendor -R && sudo chown -R "$(id -nu)" vendor
