framework:
    cache:
        directory: '%kernel.cache_dir%/pools'
        default_pdo_provider: 'doctrine.dbal.default_connection'

        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system
