framework:
    secret: '%env(APP_SECRET)%'
    session:
        enabled: true
        handler_id: session.handler.native_file
        storage_factory_id: session.storage.factory.native
        cookie_secure: auto
        cookie_samesite: lax
        cookie_lifetime: 86400
        use_cookies: true
    php_errors:
        log: true
    translator:
        default_path: '%cms.core_dir%/Cms/Platform/Infrastructure/Framework/Resources/translations'
    error_controller: Tulia\Cms\Platform\UserInterface\Web\Controller\ErrorController::handle
