framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/Website/Infrastructure/Framework/Resources/translations'
    templating:
        paths:
            - { name: backend/website, path: '%cms.core_dir%/Cms/Website/Infrastructure/Framework/Resources/views/backend' }
