framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/Website/Infrastructure/Framework/Resources/translations'
twig:
    paths:
        '%cms.core_dir%/Cms/Website/Infrastructure/Framework/Resources/views': 'website'
cms:
    templating:
        paths:
            - { name: backend/website, path: '%cms.core_dir%/Cms/Website/Infrastructure/Framework/Resources/views/backend' }
