services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $environment: '%kernel.environment%'
            $cacheDir: '%kernel.cache_dir%'

    Tulia\Cms\Website\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Platform\Infrastructure\Framework\Routing\Website\WebsiteRegistryInterface:
        '@Tulia\Cms\Website\Infrastructure\Persistence\Doctrine\Dbal\DbalWebsiteRegistry'
