services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $environment: '%kernel.environment%'

    Tulia\Cms\Website\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Component\Routing\Website\WebsiteRegistryInterface:
        '@Tulia\Cms\Website\Infrastructure\Persistence\LocalStorage\LocalStorageWebsiteRegistry'
