<?php

declare(strict_types=1);

namespace Tulia\Cms\Platform\UserInterface\Console\Command;

use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Question\Question;
use Symfony\Component\Console\Style\SymfonyStyle;
use Tulia\Cms\Platform\Domain\Service\DynamicConfigurationInterface;
use Tulia\Cms\Shared\Domain\WriteModel\UuidGeneratorInterface;
use Tulia\Cms\User\Application\UseCase\CreateUser;
use Tulia\Cms\User\Application\UseCase\CreateUserRequest;

/**
 * @author Adam Banaszkiewicz
 */
class Setup extends Command
{
    public function __construct(
        private string $rootDir,
        private UuidGeneratorInterface $uuidGenerator,
        private DynamicConfigurationInterface $configuration,
        private CreateUser $createUser
    ) {
        parent::__construct();
    }

    protected function configure()
    {
        $this
            ->setName('setup')
            ->setDescription('Setups the new project.')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);

        $io->writeln(<<<EOF
<fg=#0088cc>
████████╗██╗   ██╗██╗     ██╗ █████╗      ██████╗███╗   ███╗███████╗
╚══██╔══╝██║   ██║██║     ██║██╔══██╗    ██╔════╝████╗ ████║██╔════╝
   ██║   ██║   ██║██║     ██║███████║    ██║     ██╔████╔██║███████╗
   ██║   ██║   ██║██║     ██║██╔══██║    ██║     ██║╚██╔╝██║╚════██║
   ██║   ╚██████╔╝███████╗██║██║  ██║    ╚██████╗██║ ╚═╝ ██║███████║
   ╚═╝    ╚═════╝ ╚══════╝╚═╝╚═╝  ╚═╝     ╚═════╝╚═╝     ╚═╝╚══════╝
</>
              Welcome in the World of Tulia CMS!

EOF
);

        $io->writeln('<comment>Now, answer some questions to initialize Your Tulia CMS installation.</comment>');

        $websiteName = $this->askFor('Website name', $input, $output);
        $websiteProductionDomain = $this->askFor('Website production domain', $input, $output, default: 'localhost');
        $username = $this->askFor('Admin email', $input, $output, validator: static function ($answer) {
            if (!filter_var($answer, FILTER_VALIDATE_EMAIL)) {
                throw new \RuntimeException('Please provide a valid e-mail address.');
            }
        });
        $password = $this->askFor('Admin password', $input, $output, default: 'root', hidden: true);
        $sampleData = $this->askFor('I want to load sample website data', $input, $output, default: 'yes');

        $this->updateWebsite($websiteName, $websiteProductionDomain);
        $this->crreateAdminUser($username, $password);

        if (!($_ENV['APP_SECRET'] ?? null)) {
            $secret = $this->uuidGenerator->generate();
            $this->appendToDotenv('APP_SECRET', $secret);

            $output->writeln(sprintf('<info>Autogenerated APP_SECRET is %s.</info>', $secret));
        }

        $output->writeln('<info>Tulia CMS installed. Go to http://localhost/ to start new adventure!</info>');

        return Command::SUCCESS;
    }

    private function appendToDotenv(string $variable, string $value): void
    {
        $lines = file($this->rootDir.'/.env');
        $found = false;

        foreach ($lines as $no => $line) {
            if (strpos($line, "$variable=") === 0) {
                $lines[$no] = "$variable=$value\n";
                $found = true;
            }
        }

        if ($found === false) {
            $lines[] = "$variable=$value\n";
        }

        file_put_contents($this->rootDir.'/.env', implode('', $lines));
    }

    private function askFor(
        string $questionMessage,
        InputInterface $input,
        OutputInterface $output,
        callable $validator = null,
        mixed $default = '',
        bool $required = true,
        bool $hidden = false,
    ): string {
        if ($default) {
            $defaultValue = sprintf(' <fg=#eeeeee>(%s)</>', $default);
        } else {
            $defaultValue = '';
        }

        $question = new Question(sprintf('%s%s: ', $questionMessage, $defaultValue), $default);
        $question->setHidden($hidden);
        $question->setValidator(function ($answer) use ($questionMessage, $required, $validator) {
            if ($required && empty($answer)) {
                throw new \RuntimeException(sprintf('Please provide a %s.', strtolower($questionMessage)));
            }

            if (is_callable($validator)) {
                $validator($answer);
            }

            return $answer;
        });
        return $this->getHelper('question')->ask($input, $output, $question);
    }

    private function updateWebsite(string $websiteName, string $websiteProductionDomain): void
    {
        $this->configuration->open();
        $website = $this->configuration->get('cms.website');
        $website['locales'][0]['domain'] = $websiteProductionDomain;
        $this->configuration->set('cms.website', $website);
    }

    private function crreateAdminUser(string $username, string $password): void
    {
        ($this->createUser)(new CreateUserRequest(
            $username,
            $password,
            ['ROLE_ADMIN']
        ));
    }
}
