_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix: /_error

backend._preview_error:
    controller: error_controller::preview
    path: /_error/{code}.{_format}
    defaults:
        _format: html
    requirements:
        code: \d+
