framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/Node/Infrastructure/Internal/Framework/Resources/translations'

doctrine:
    orm:
        mappings:
            Tulia\Cms\Node\Domain\WriteModel\Model:
                type: xml
                dir: '%cms.core_dir%/Cms/Node/Infrastructure/Internal/Framework/Resources/config/orm/mapping'
                is_bundle: false
                prefix: Tulia\Cms\Node\Domain\WriteModel\Model
                alias: CmsNode

cms:
    templating:
        paths:
            - { name: backend/node, path: '%cms.core_dir%/Cms/Node/Infrastructure/Internal/Framework/Resources/views/backend' }
            - { name: cms/node, path: '%cms.core_dir%/Cms/Node/Infrastructure/Internal/Framework/Resources/views/frontend' }
    importer:
        objects:
            Node:
                importer: 'Tulia\Cms\Node\Infrastructure\Internal\Importer\NodeEntryImporter'
                mapping:
                    parent_id:
                        type: uuid
                    type:
                        required: true
                    status:
                        default_value: published
                    published_at:
                        type: datetime
                    published_to:
                        type: datetime
                    created_at:
                        type: datetime
                    updated_at:
                        type: datetime
                    title:
                        required: true
                    slug: ~
                    purposes:
                        type: array
                    attributes:
                        collection_of: Attribute
    filemanager:
        image_sizes:
            - { name: node-thumbnail, width: 450, height: 300 }
    content_building:
        content_type:
            node:
                controller: 'Tulia\Cms\Node\UserInterface\Web\Frontend\Controller\Node::show'
                layout_builder: 'Tulia\Cms\Content\Type\Infrastructure\Presentation\TwigRoutableContentTypeLayoutBuilder'
        data_types:
            mapping:
                node_select:
                    label: Node Typehead
                    classname: 'Tulia\Cms\Node\UserInterface\Web\Shared\Form\FormType\NodeTypeaheadType'
                    builder: 'Tulia\Cms\Node\UserInterface\Web\Shared\Form\FormType\NodeTypeaheadTypeBuilder'
                    constraints: [required]
