services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Node\:
        resource: '../../../../../**'
        exclude: '../../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Node\Domain\WriteModel\Service\NodePurpose\NodePurposeRegistryInterface:
        class: Tulia\Cms\Node\Domain\WriteModel\Service\NodePurpose\NodePurposeRegistry
        bind:
            $providers: !tagged_iterator node.purpose_provider

    Tulia\Cms\Node\Infrastructure\Internal\Framework\Routing\SymfonyRouter:
        tags: [ routing_chain.router ]

    Tulia\Cms\Node\Infrastructure\Internal\Menu\IdentityProvider:
        tags: [ menu.identity_provider ]

    Tulia\Cms\Node\Infrastructure\Internal\Settings\SettingsFactory:
        tags: [ settings.group_factory ]

    Tulia\Cms\Node\Infrastructure\Internal\SearchAnything\SearchProvider:
        tags:
            - { name: search.provider, priority: 1000 }

    Tulia\Cms\Node\Domain\WriteModel\Rules\CanAddPurpose\CanImposePurposeInterface:
        class: Tulia\Cms\Node\Domain\WriteModel\Rules\CanAddPurpose\CanImposePurpose
