services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Node\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Node\Domain\NodeFlag\NodeFlagRegistryInterface:
        class: Tulia\Cms\Node\Domain\NodeFlag\NodeFlagRegistry
        bind:
            $providers: !tagged_iterator node.flag_provider

    Tulia\Cms\Node\Infrastructure\Framework\Routing\SymfonyRouter:
        tags: [ routing_chain.router ]

    Tulia\Cms\Node\Infrastructure\Menu\IdentityProvider:
        tags: [ menu.identity_provider ]

    Tulia\Cms\Node\UserInterface\Web\Backend\Settings\SettingsFactory:
        tags: [ settings.group_factory ]

    Tulia\Cms\Node\Infrastructure\Cms\SearchAnything\SearchProvider:
        tags:
            - { name: search.provider, priority: 1000 }
