framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/Menu/Infrastructure/Framework/Resources/translations'
    cache:
        pools:
            menu.cache:
                adapter: '%tulia.cache.adapter%'
                provider: '%tulia.cache.provider%'
                default_lifetime: 86400
                tags: true
doctrine:
    orm:
        mappings:
            Tulia\Cms\Menu\Domain\WriteModel\Model:
                type: xml
                dir: '%cms.core_dir%/Cms/Menu/Infrastructure/Framework/Resources/config/orm/mapping'
                is_bundle: false
                prefix: Tulia\Cms\Menu\Domain\WriteModel\Model
                alias: CmsMenu
cms:
    templating:
        paths:
            - { name: backend/menu, path: '%cms.core_dir%/Cms/Menu/Infrastructure/Framework/Resources/views/backend' }
    content_building:
        data_types:
            mapping:
                menu_select:
                    label: Menu
                    classname: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
                    builder: 'Tulia\Cms\Menu\Infrastructure\Framework\Form\FormType\MenuSelectTypeBuilder'
                    constraints: [ required ]
                menu_layout:
                    label: Menu layout
                    classname: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
                    builder: 'Tulia\Cms\Menu\Infrastructure\Framework\Form\FormType\MenuLayoutTypeBuilder'
                    constraints: [ required ]
        content_type:
            menu_item:
                layout_builder: 'Tulia\Cms\Menu\Infrastructure\Presentation\TwigMenuItemContentTypeLayoutBuilder'
                multilingual: false
                configurable: false
        content_type_entry:
            menu_item:
                type: menu_item
                name: Menu items
                icon: null
                controller: null
                is_routable: false
                is_hierarchical: false
                routing_strategy: null
                layout: ~

    widgets:
        internal.menu:
            classname: 'Tulia\Cms\Menu\Infrastructure\Cms\Widget\Menu\MenuWidget'
            name: widget.menu.name
            views: '%cms.core_dir%/Cms/Menu/Infrastructure/Framework/Resources/views/widget/menu'
            description: widget.menu.description
            translation_domain: widgets
            fields:
                menu_id:
                    type: menu_select
                    name: Menu
                layout:
                    type: menu_layout
                    name: Menu layout
