services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tulia\Cms\ContentBuilder\Layout\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/**'
            - '../../../../Domain/**/Model/**'
            - '../../../../Domain/**/Exception/**'
            - '../../../../UserInterface/LayoutType/Model/**'
