services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Tulia\Cms\Content\Type\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources/**'
            - '../../../../Domain/**/Model/**'
            - '../../../../Domain/**/Exception/**'
            - '../../../../UserInterface/LayoutType/Model/**'

    Tulia\Cms\Content\Type\Infrastructure\Persistence\ContentProvider\ContentTypeContainerProvider:
        arguments:
            $configuration: '%cms.content_builder.content_type_entry.config%'

    Tulia\Cms\Content\Type\UserInterface\Web\Backend\Form\FormHandler:
        shared: false

    Tulia\Cms\Content\Type\Domain\WriteModel\Service\Configuration:
        arguments:
            $configuration: '%cms.content_builder.content_type.config%'

    Tulia\Cms\Content\Type\Domain\ReadModel\Service\ContentTypeRegistryInterface:
        class: Tulia\Cms\Content\Type\Infrastructure\Persistence\ContentProvider\CachedContentTypeRegistry

