cms:
    importer:
        objects:
            Attribute:
                mapping:
                    payload:
                        required: false
                        type: string
                    code: ~
                    uri: ~
                    value:
                        type: string
doctrine:
    orm:
        mappings:
            Tulia\Cms\Content\Attributes\Domain\WriteModel\Model:
                type: xml
                dir: '%cms.core_dir%/Cms/Content/Attributes/Infrastructure/Framework/Resources/config/orm/mapping'
                is_bundle: false
                prefix: Tulia\Cms\Content\Attributes\Domain\WriteModel\Model
                alias: CmsContentAttribute
    dbal:
        types:
            cms_content_attribute_value: Tulia\Cms\Content\Attributes\Infrastructure\Persistence\Doctrine\DBAL\Type\ContentAttributeValueType

