cms:
    importer:
        objects:
            Attribute:
                type: collection_item
                mapping:
                    payload:
                        required: false
                        type: string
                    code: ~
                    uri: ~
                    value:
                        type: string
                    values:
                        type: array
doctrine:
    orm:
        mappings:
            Tulia\Cms\Content\Attributes\Domain\WriteModel\Model:
                type: xml
                dir: '%cms.core_dir%/Cms/Content/Attributes/Infrastructure/Framework/Resources/config/orm/mapping'
                is_bundle: false
                prefix: Tulia\Cms\Content\Attributes\Domain\WriteModel\Model
                alias: CmsContentAttribute
