cms:
    importer:
        objects:
            Attribute:
                mapping:
                    payload:
                        required: false
                        type: string
                    code: ~
                    uri: ~
                    value:
                        type: string
