doctrine:
    orm:
        mappings:
            Tulia\Cms\Filemanager\Domain\WriteModel\Model:
                type: xml
                dir: '%cms.core_dir%/Cms/Filemanager/Infrastructure/Framework/Resources/config/orm/mapping'
                is_bundle: false
                prefix: Tulia\Cms\Filemanager\Domain\WriteModel\Model
                alias: CmsFilemanager
cms:
    importer:
        objects:
            File:
                importer: 'Tulia\Cms\Filemanager\Infrastructure\Cms\Importer\FileImporter'
                mapping:
                    filepath: ~
    templating:
        paths:
            - { name: backend/filemanager, path: '%cms.core_dir%/Cms/Filemanager/Infrastructure/Framework/Resources/views/backend' }
    public_paths:
        - { source: '%cms.core_dir%/Cms/Filemanager/Infrastructure/Framework/Resources/public/filemanager/dist', target: '/core/filemanager' }
        - { source: '%cms.core_dir%/Cms/Filemanager/Infrastructure/Framework/Resources/public/filemanager.dynamic-form', target: '/core/filemanager.dynamic-form' }
    assetter:
        assets:
            filemanager:
                styles: [ '/assets/core/filemanager/main.css' ]
                scripts:
                    - '/assets/core/filemanager/tulia-filemanager.js'
                require: [ 'jquery', 'jstree', 'fileapi' ]
                group: head
#            filemanager:
#                styles: [ '/assets/core/filemanager/css/filemanager.css' ]
#                scripts:
#                    - '/assets/core/filemanager/js/src/variables.js'
#                    - '/assets/core/filemanager/js/src/front-controller.js'
#                    - '/assets/core/filemanager/js/src/command-bus.js'
#                    - '/assets/core/filemanager/js/src/container.js'
#                    - '/assets/core/filemanager/js/src/directory-tree.js'
#                    - '/assets/core/filemanager/js/src/event-dispatcher.js'
#                    - '/assets/core/filemanager/js/src/files-collection.js'
#                    - '/assets/core/filemanager/js/src/manager.js'
#                    - '/assets/core/filemanager/js/src/model.js'
#                    - '/assets/core/filemanager/js/src/selection.js'
#                    - '/assets/core/filemanager/js/src/view.js'
#                    - '/assets/core/filemanager/js/src/cache.js'
#                    - '/assets/core/filemanager/js/src/upload.js'
#                    - '/assets/core/filemanager/js/src/config.js'
#                require: [ 'jquery', 'jstree', 'fileapi' ]
#                group: head
            filemanager.dynamic_form_plugin:
                scripts: [ '/assets/core/filemanager.dynamic-form/filemanager.dynamic-form-plugin.js' ]
                collection: tulia-dynamic-form
                require: [ filemanager, tulia_dynamic_form ]
    filemanager:
        image_sizes:
            - { name: thumbnail, width: 200, mode: widen }
            - { name: thumbnail-md, width: 400, mode: widen }
