framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/ContactForm/Infrastructure/Framework/Resources/translations'
doctrine:
    orm:
        mappings:
            Tulia\Cms\ContactForm\Domain\WriteModel\Model:
                type: xml
                dir: '%cms.core_dir%/Cms/ContactForm/Infrastructure/Framework/Resources/config/orm/mapping'
                is_bundle: false
                prefix: Tulia\Cms\ContactForm\Domain\WriteModel\Model
                alias: CmsForm
cms:
    importer:
        objects:
            ContactForm:
                importer: 'Tulia\Cms\ContactForm\Infrastructure\Cms\Importer\ContactFormImporter'
                mapping:
                    name: ~
                    receivers:
                        type: array
                    sender_name:
                        required: false
                    sender_email: ~
                    subject: ~
                    message_template: ~
                    fields_template: ~
                    fields:
                        collection_of: ContactFormField
            ContactFormField:
                mapping:
                    type: ~
                    name: ~
                    options:
                        type: array
    templating:
        paths:
            - { name: cms/forms, path: '%cms.core_dir%/Cms/ContactForm/Infrastructure/Framework/Resources/views/frontend' }
            - { name: backend/forms, path: '%cms.core_dir%/Cms/ContactForm/Infrastructure/Framework/Resources/views/backend' }
    public_paths:
        - { source: '%cms.core_dir%/Cms/ContactForm/Infrastructure/Framework/Resources/public/contact-form-builder/dist', target: '/core/contact-forms' }
    assetter:
        assets:
            tulia.contact_forms:
                scripts:
                    - /assets/core/contact-forms/js/build.js
    widgets:
        internal.contact_form:
            classname: 'Tulia\Cms\ContactForm\Infrastructure\Cms\Widget\Predefined\ContactFormWidget'
            name: widget.name
            views: '%cms.core_dir%/Cms/ContactForm/Infrastructure/Framework/Resources/views/widgets/contact-form'
            description: widget.description
            translation_domain: contact-form
            fields:
                form_id:
                    type: contact_form
                    name: form
    content_blocks:
        templating:
            paths:
                - '@cms/forms/content-block'
    content_building:
        data_types:
            mapping:
                contact_form:
                    label: Contact form select
                    classname: 'Symfony\Component\Form\Extension\Core\Type\ChoiceType'
                    builder: 'Tulia\Cms\ContactForm\UserInterface\Web\Shared\Form\FormType\FormSelectorBuilder'
                    constraints: [ required ]
        content_type_entry:
            contact_form:
                type: content_block
                name: Contact form
                icon: null
                controller: null
                is_routable: false
                is_hierarchical: false
                routing_strategy: null
                layout:
                    sections:
                        main:
                            groups:
                                fields_group:
                                    name: fields
                                    active: true
                                    order: 0
                                    fields:
                                        form_id:
                                            type: contact_form
                                            name: Form to show
                                            configuration:
                                                - { code: icon, value: /assets/theme/tulia/lisa/images/content-block/icon/company-in-numbers.png }
                                            constraints:
                                                -
                                                    code: required
                                                -
                                                    code: length
                                                    modificators:
                                                        - { code: min, value: 0 }
                                                        - { code: max, value: 127 }
