backend.theme:
    path: /administrator/theme/list
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Theme::index

backend.theme.activate:
    path: /administrator/theme/activate
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Theme::activate
    methods: POST

backend.theme.installator.install:
    path: /administrator/theme/installator/install
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Installator::install
    methods: POST

backend.theme.installator.uninstall:
    path: /administrator/theme/installator/uninstall
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Installator::uninstall
    methods: POST

backend.theme.customize.current:
    path: /administrator/theme/customize
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::customizeRedirect

backend.theme.customize.left:
    path: /administrator/theme/customize/left/{changeset}
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::left

backend.theme.customize.reset:
    path: /administrator/theme/customize/reset/{theme}
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::reset
    requirements:
        theme: '([a-zA-Z0-9]+\/[a-zA-Z0-9]+)'

backend.theme.customize.copy_changeset_from_parent:
    path: /administrator/theme/customize/copy-changeset-from-parent/{theme}
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::copyChangesetFromParent
    requirements:
        theme: '([a-zA-Z0-9]+\/[a-zA-Z0-9]+)'

backend.theme.customize.save:
    path: /administrator/theme/customize/save/{theme}/{changeset}
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::save
    methods: POST|GET
    requirements:
        theme: '([a-zA-Z0-9]+\/[a-zA-Z0-9]+)'

backend.theme.customize:
    path: /administrator/theme/customize/{theme}/{changeset}
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::customize
    requirements:
        theme: '([a-zA-Z0-9]+\/[a-zA-Z0-9]+)'
    defaults:
        changeset: null
