backend.theme:
    path: /administrator/theme/list
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Theme::index

backend.theme.activate:
    path: /administrator/theme/activate
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Theme::activate
    methods: POST

backend.theme.preview:
    path: /administrator/theme/preview/{theme}/{page}
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Theme::preview
    requirements:
        theme: '([a-zA-Z0-9]+\/[a-zA-Z0-9]+)'
        page: .+
    methods: GET

backend.theme.installator.install:
    path: /administrator/theme/installator/install
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Installator::install
    methods: POST

backend.theme.installator.publish_assets:
    path: /administrator/theme/installator/publish-assets
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Installator::publishAssetsAfterInstallation

backend.theme.installator.importer:
    path: /administrator/theme/installator/importer
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Installator::importer

backend.theme.installator.importer.import:
    path: /administrator/theme/installator/importer/import
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Installator::import
    methods: POST

backend.theme.installator.uninstall:
    path: /administrator/theme/installator/uninstall
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Installator::uninstall
    methods: POST

backend.theme.customize.left:
    path: /administrator/theme/customize/{theme}/left/{changeset}
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::left
    requirements:
        theme: '([a-zA-Z0-9]+\/[a-zA-Z0-9]+)'

backend.theme.customize.reset:
    path: /administrator/theme/customize/{theme}/reset
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::reset
    requirements:
        theme: '([a-zA-Z0-9]+\/[a-zA-Z0-9]+)'

backend.theme.customize.copy_changeset_from_parent:
    path: /administrator/theme/customize/{theme}/copy-changeset-from-parent
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::copyChangesetFromParent
    requirements:
        theme: '([a-zA-Z0-9]+\/[a-zA-Z0-9]+)'

backend.theme.customize.save:
    path: /administrator/theme/customize/{theme}/save
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::save
    methods: POST|GET
    requirements:
        theme: '([a-zA-Z0-9]+\/[a-zA-Z0-9]+)'

backend.theme.customize:
    path: /administrator/theme/customize
    controller: Tulia\Cms\Theme\UserInterface\Web\Backend\Controller\Customizer::customize
