services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $filesTemplates: '%cms.core_dir%/Cms/Theme/Infrastructure/Framework/Resources/maker/file-templates'
            $fontsPath: '%cms.core_dir%/Cms/Theme/Infrastructure/Framework/Resources/fonts'
            $projectDir: '%kernel.project_dir%'

    Tulia\Cms\Theme\:
        resource: '../../../../**'
        exclude:
        exclude: '../../../../{Infrastructure/Framework/Resources,UI/Web/Controller/Backend/Theme.php}'

    Tulia\Component\Theme\Loader\ThemeLoader\ThemeLoaderInterface:
        class: Tulia\Cms\Theme\Infrastructure\Framework\Theme\Loader\ThemeLoader
        bind:
            $configFilename: '%kernel.project_dir%/config/dynamic.php'

    Tulia\Cms\Theme\Infrastructure\Filemanager\ImageSize\ThemeConfigurationImagesSizeProvider:
        tags: [ filemanager.image_size.provider ]

    Tulia\Component\Theme\Customizer\Changeset\Storage\StorageInterface:
        class: Tulia\Cms\Theme\Infrastructure\Framework\Theme\Customizer\Changeset\Storage\DatabaseStorage

    Tulia\Component\Theme\Customizer\Changeset\Factory\ChangesetFactoryInterface:
        class: Tulia\Component\Theme\Customizer\Changeset\Factory\ChangesetFactory
        bind:
            $classname: \Tulia\Cms\Theme\Infrastructure\Framework\Theme\Customizer\Changeset\Changeset
