framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/Settings/Infrastructure/Framework/Resources/translations'
cms:
    templating:
        paths:
            - { name: backend/settings, path: '%cms.core_dir%/Cms/Settings/Infrastructure/Framework/Resources/views/backend' }
    options:
        definitions:
            website_favicon:
            administrator_email:
                value: admin@domain.com
            maintenance_mode:
                autoload: true
            maintenance_message:
                value: 'Page is under maintenance mode. Please come back later.'
                multilingual: true
            date_format:
                autoload: true
            wysiwyg_editor:
                autoload: true
            mail.transport:
                value: smtp
            mail.from_email:
                value: admin@domain.com
            mail.from_name:
                value: Website administrator
            mail.host:
                value: tuliacms_tulia_mailhog_1 # Mailhog Docker's container name
            mail.port:
                value: 1025
            mail.username:
            mail.password:
            mail.encryption:
            mail.sendmailpath:
            url_suffix:
                autoload: true
