framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/Settings/Infrastructure/Framework/Resources/translations'
    cache:
        pools:
            settings.cache:
                adapter: '%tulia.cache.adapter%'
                provider: '%tulia.cache.provider%'
                default_lifetime: 31556926
                tags: true
cms:
    templating:
        paths:
            - { name: backend/settings, path: '%cms.core_dir%/Cms/Settings/Infrastructure/Framework/Resources/views/backend' }
    options:
        definitions:
            theme:
                autoload: true
            website_favicon:
            administrator_email:
                value: admin@domain.com
            maintenance_mode:
                autoload: true
            maintenance_message:
                value: 'Page is under maintenance mode. Please come back later.'
                multilingual: true
            date_format:
                autoload: true
            wysiwyg_editor:
                autoload: true
                value: quill
            mail.transport:
                value: smtp
            mail.from_email:
                value: admin@domain.com
            mail.from_name:
                value: Website administrator
            mail.host:
                value: tuliacms-tulia_mailhog-1 # Mailhog Docker's container name
            mail.port:
                value: 1025
            mail.username:
            mail.password:
            mail.encryption:
            mail.sendmailpath:
            url_suffix:
                autoload: true
    search_anything:
        indexes:
            settings:
                localization_strategy: user
                multisite_strategy: website
                collector: Tulia\Cms\Settings\Infrastructure\Cms\SearchAnything\SettingsDocumentCollector
