services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Settings\:
        resource: '../../../../**'
        exclude: '../../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\Settings\Domain\Group\SettingsGroupRegistryInterface:
        class: Tulia\Cms\Settings\Domain\Group\SettingsRegistryRegistry
        bind:
            $factories: !tagged_iterator settings.group_factory
            $groups: !tagged_iterator settings.group
