framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/Taxonomy/Infrastructure/Framework/Resources/translations'
    cache:
        pools:
            cache.taxonomy:
                adapter: '%tulia.cache.adapter%'
                provider: '%tulia.cache.provider%'
                default_lifetime: 2592000
                tags: true
doctrine:
    orm:
        mappings:
            Tulia\Cms\Taxonomy\Domain\WriteModel\Model:
                type: xml
                dir: '%cms.core_dir%/Cms/Taxonomy/Infrastructure/Framework/Resources/config/orm/mapping'
                is_bundle: false
                prefix: Tulia\Cms\Taxonomy\Domain\WriteModel\Model
                alias: CmsTaxonomy
cms:
    templating:
        paths:
            - { name: backend/taxonomy, path: '%cms.core_dir%/Cms/Taxonomy/Infrastructure/Framework/Resources/views/backend' }
            - { name: cms/taxonomy, path: '%cms.core_dir%/Cms/Taxonomy/Infrastructure/Framework/Resources/views/frontend' }
    content_building:
        content_type:
            taxonomy:
                controller: 'Tulia\Cms\Taxonomy\UserInterface\Web\Frontend\Controller\Term::show'
                layout_builder: 'Tulia\Cms\Content\Type\Infrastructure\Presentation\TwigRoutableContentTypeLayoutBuilder'
        data_types:
            mapping:
                taxonomy:
                    label: Taxonomy
                    classname: 'Tulia\Cms\Taxonomy\UserInterface\Web\Shared\Form\FormType\TaxonomyTypeaheadType'
                    builder: 'Tulia\Cms\Taxonomy\UserInterface\Web\Shared\Form\FormType\TaxonomyTypeaheadTypeBuilder'
                    constraints: [ required ]
                    configuration:
                        taxonomy:
                            type: choice
                            label: Select type of taxonomy
                            required: true
                            choices_provider: 'Tulia\Cms\Taxonomy\UserInterface\Web\Shared\Form\FormType\TaxonomyTypeaheadTypeChoicesProvider'
    importer:
        objects:
            Term:
                importer: 'Tulia\Cms\Taxonomy\Infrastructure\Cms\Import\TermImporter'
                exporter: 'Tulia\Cms\Taxonomy\Infrastructure\Cms\Import\TermExporter'
                mapping:
                    type:
                        required: true
                    name:
                        required: true
                    slug: ~
                    parent_id: ~
                    position:
                        type: int
                    attributes:
                        collection_of: Attribute
