backend.term.search.typeahead:
    path: /term/search/typeahead
    controller: Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Controller\TypeaheadSearch::handleSearch

backend.term.datatable:
    path: /term/{taxonomyType}/datatable
    controller: Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Controller\Term::datatable

backend.term.create:
    path: /term/{taxonomyType}/create
    controller: Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Controller\Term::create
    methods: GET|POST

backend.term.edit:
    path: /term/{taxonomyType}/edit/{id}
    controller: Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Controller\Term::edit
    methods: GET|POST

backend.term.delete:
    path: /term/{taxonomyType}/delete
    controller: Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Controller\Term::delete
    methods: POST

backend.term.list:
    path: /term/{taxonomyType}/list
    controller: Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Controller\Term::list

backend.term.hierarchy:
    path: /term/{taxonomyType}/hierarchy
    controller: Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Controller\Hierarchy::index
    defaults:
        taxonomyType: category

backend.term.hierarchy.save:
    path: /term/{taxonomyType}/hierarchy/save
    controller: Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Controller\Hierarchy::save
    defaults:
        taxonomyType: category
    methods: POST

backend.term:
    path: /term/{taxonomyType}
    controller: Tulia\Cms\Taxonomy\UserInterface\Web\Backend\Controller\Term::index
