services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\Taxonomy\:
        resource: '../../../../**'
        exclude:
            - '../../../../Infrastructure/Framework/Resources'
            - '../../../../Infrastructure/Cms/Settings/TaxonomyTypeSettingsGroup.php'
