services:
    _defaults:
        autowire: true
        autoconfigure: true

    Tulia\Cms\BackendMenu\:
        resource: '../../../**'
        exclude: '../../../{Infrastructure/Framework/Resources}'

    Tulia\Cms\BackendMenu\Builder\HtmlBuilderInterface:
        class: Tulia\Cms\BackendMenu\Builder\HtmlBuilder
        bind:
            $builders: !tagged_iterator backend_menu.builder
