imports:
    - { resource: services/assetter.yaml }
    - { resource: services/bus.yaml }
    - { resource: services/database.yaml }
    - { resource: services/datatable.yaml }
    - { resource: services/finder.yaml }
    - { resource: services/image.yaml }
    - { resource: services/importer.yaml }
    - { resource: services/mailer.yaml }
    - { resource: services/platform.yaml }
    - { resource: services/routing.yaml }
    - { resource: services/shortcode.yaml }
    - { resource: services/templating.yaml }
    - { resource: services/theme.yaml }
    - { resource: services/utils.yaml }
    - { resource: services/fixtures.yaml }
    - { resource: services/hooks.yaml }
