cms:
    templating:
        paths:
            - { name: backend/security, path: '%cms.core_dir%/Cms/Security/Framework/Resources/views/backend' }
            - { name: cms/security, path: '%cms.core_dir%/Cms/Security/Framework/Resources/views/frontend' }
framework:
    translator:
        paths:
            - '%cms.core_dir%/Cms/Security/Framework/Resources/translations'
