frontend.login:
    path: /auth/login
    controller: Tulia\Cms\Security\Controller\Frontend\Security::login
    methods: GET|POST

frontend.logout:
    path: /auth/logout
    controller: Tulia\Cms\Security\Controller\Frontend\Security::logout

backend.login:
    path: /auth/login
    controller: Tulia\Cms\Security\Controller\Backend\Security::login
    methods: GET|POST

backend.logout:
    path: /auth/logout
    controller: Tulia\Cms\Security\Controller\Backend\Security::logout
    methods: GET|POST

backend.security.verify_password:
    path: /security/verify-password
    controller: Tulia\Cms\Security\Controller\Backend\Security::verifyPassword
